---
- hosts: localhost
  tasks:
    - name: remove redundant packages
      ansible.builtin.apt:
          autoremove: yes
          force_apt_get: yes
    - name: Autojump activation bash
      ansible.builtin.lineinfile:
        path: "~{{ local_username }}/.bashrc"
        line: "{{ item }}"
        create: yes
      with_items: 
       - . /usr/share/autojump/autojump.sh
    - name: Autojump activation fish
      ansible.builtin.lineinfile:
        path: "~{{ local_username }}/.config/fish/config.fish"
        line: "{{ item }}"
        create: yes
      with_items: 
       - . /usr/share/autojump/autojump.fish
         # - name: Autojump activation fish
         #ansible.builtin.lineinfile:
         #path: "~{{ local_username }}/.config/fish/config.fish"
         #line: "{{ item }}"
         # create: yes
         #with_items: 
         #- . /usr/share/autojump/autojump.fish
    # add user to docker group to run docker commands without sudo
    # add user to vboxusers group so that user can attach usb devices to guest OS
    - name: add user to docker and vboxusers groups
      ansible.builtin.user:
        name: "{{ local_username }}"
        append: yes
        groups:
          - docker
          - vboxusers
      become: yes
      become_user: root

    - name: display post install message
      debug:
        msg:
          - 'Manual steps left to do:'
          - '- git clone the dotfiles repo (optional)'
          - '- add noatime option for your SSD mounts points in /etc/fstab (optional)'
          - '- enable WebRender in firefox; about:config in address bar, then manually set the gfx.webrender.enabled or gfx.webrender.all pref to true (optional)'
          - '- cache in RAM only in firefox: about:config, browser.cache.disk.enable -> false, browser.cache.memory.enable -> true, browser.cache.memory.capacity -> 1048576, browser.cache.memory.max_entry_size -> 51200, verify using about:cache in address bar (optional)'
          - '- Reboot your system'

...
