---
- name: Install awesome & packages
  ansible.builtin.apt:
    name: "{{ awesome_packages }}"
    state: present
    force_apt_get: yes
- name: Cria awesome config dir
  ansible.builtin.command: mkdir -p ~/.config/awesome/
  become_user: "{{local_username}}"
- name: Clone awesome-wm-widgets
  ansible.builtin.git:
    repo: "https://github.com/streetturtle/awesome-wm-widgets"
    dest: "~{{ local_username }}/.config/awesome/awesome-wm-widgets"
  become_user: "{{ local_username }}"
- name: Clone lain
  ansible.builtin.git:
    repo: "https://github.com/lcpz/lain"
    dest: "~{{ local_username }}/.config/awesome/lain"
  become_user: "{{ local_username }}"
- name: Clone awesomewm themes
  ansible.builtin.git:
    repo: "https://github.com/lcpz/awesome-copycats"
    dest: "~{{ local_username }}/.config/awesome/awesome-copycats"
    depth: 1
  become_user: "{{ local_username }}"
- name: Download json.lua
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/rxi/json.lua/master/json.lua'
    dest: ~/.config/awesome/json.lua
    mode: '644'
  become_user: "{{local_username}}"
- name: Download awesome config
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/edueo/config/main/rc.lua'
    dest: ~/.config/awesome/rc.lua
    mode: '644'
  become_user: "{{local_username}}"
