---
- name: Install awesome & packages
  ansible.builtin.apt:
    name: "{{ awesome_packages }}"
    state: present
    force_apt_get: yes
- name: Cria awesome config dir
  ansible.builtin.command: mkdir -p ~/.config/awesome/
  become_user: "{{local_username}}"
- name: Download awesome config
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/edueo/config/main/rc.lua'
    dest: ~/.config/awesome/rc.lua
    mode: '644'
  become_user: "{{local_username}}"